#ifndef GPSDO_READER_H
#define GPSDO_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct gpsdo_Status_table *gpsdo_Status_table_t;
typedef struct gpsdo_Status_table *gpsdo_Status_mutable_table_t;
typedef const flatbuffers_uoffset_t *gpsdo_Status_vec_t;
typedef flatbuffers_uoffset_t *gpsdo_Status_mutable_vec_t;
#ifndef gpsdo_Status_file_identifier
#define gpsdo_Status_file_identifier 0
#endif
/* deprecated, use gpsdo_Status_file_identifier */
#ifndef gpsdo_Status_identifier
#define gpsdo_Status_identifier 0
#endif
#define gpsdo_Status_type_hash ((flatbuffers_thash_t)0x5052a732)
#define gpsdo_Status_type_identifier "\x32\xa7\x52\x50"
#ifndef gpsdo_Status_file_extension
#define gpsdo_Status_file_extension "bin"
#endif



struct gpsdo_Status_table { uint8_t unused__; };

static inline size_t gpsdo_Status_vec_len(gpsdo_Status_vec_t vec)
__flatbuffers_vec_len(vec)
static inline gpsdo_Status_table_t gpsdo_Status_vec_at(gpsdo_Status_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(gpsdo_Status_table_t, vec, i, 0)
__flatbuffers_table_as_root(gpsdo_Status)

__flatbuffers_define_scalar_field(0, gpsdo_Status, freq_error_Hz, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(1, gpsdo_Status, freq_dirft_HzDs, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(2, gpsdo_Status, voltage_control_V, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(3, gpsdo_Status, voltage_measured_V, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(4, gpsdo_Status, temperature_C, flatbuffers_float, float, 0.00000000f)


#include "flatcc/flatcc_epilogue.h"
#endif /* GPSDO_READER_H */
