#ifndef GPSDO_VERIFIER_H
#define GPSDO_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef GPSDO_READER_H
#include "gpsdo_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int gpsdo_Status_verify_table(flatcc_table_verifier_descriptor_t *td);

static int gpsdo_Status_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* phase_cnt */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* freq_error_hz */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* freq_drift_hz_s */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 4, 4) /* voltage_control_v */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 4, 4) /* voltage_measured_v */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 4, 4) /* temperature_c */)) return ret;
    if ((ret = flatcc_verify_field(td, 6, 4, 4) /* raw_counter_value */)) return ret;
    return flatcc_verify_ok;
}

static inline int gpsdo_Status_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, gpsdo_Status_identifier, &gpsdo_Status_verify_table);
}

static inline int gpsdo_Status_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, gpsdo_Status_identifier, &gpsdo_Status_verify_table);
}

static inline int gpsdo_Status_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, gpsdo_Status_type_identifier, &gpsdo_Status_verify_table);
}

static inline int gpsdo_Status_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, gpsdo_Status_type_identifier, &gpsdo_Status_verify_table);
}

static inline int gpsdo_Status_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &gpsdo_Status_verify_table);
}

static inline int gpsdo_Status_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &gpsdo_Status_verify_table);
}

static inline int gpsdo_Status_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &gpsdo_Status_verify_table);
}

static inline int gpsdo_Status_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &gpsdo_Status_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* GPSDO_VERIFIER_H */
