# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gpsdo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Status(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Status()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatus(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Status
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Status
    def FreqErrorHz(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Status
    def FreqDirftHzDs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Status
    def VoltageControlV(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Status
    def VoltageMeasuredV(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Status
    def TemperatureC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def StatusStart(builder):
    builder.StartObject(5)

def Start(builder):
    StatusStart(builder)

def StatusAddFreqErrorHz(builder, freqErrorHz):
    builder.PrependFloat32Slot(0, freqErrorHz, 0.0)

def AddFreqErrorHz(builder, freqErrorHz):
    StatusAddFreqErrorHz(builder, freqErrorHz)

def StatusAddFreqDirftHzDs(builder, freqDirftHzDs):
    builder.PrependFloat32Slot(1, freqDirftHzDs, 0.0)

def AddFreqDirftHzDs(builder, freqDirftHzDs):
    StatusAddFreqDirftHzDs(builder, freqDirftHzDs)

def StatusAddVoltageControlV(builder, voltageControlV):
    builder.PrependFloat32Slot(2, voltageControlV, 0.0)

def AddVoltageControlV(builder, voltageControlV):
    StatusAddVoltageControlV(builder, voltageControlV)

def StatusAddVoltageMeasuredV(builder, voltageMeasuredV):
    builder.PrependFloat32Slot(3, voltageMeasuredV, 0.0)

def AddVoltageMeasuredV(builder, voltageMeasuredV):
    StatusAddVoltageMeasuredV(builder, voltageMeasuredV)

def StatusAddTemperatureC(builder, temperatureC):
    builder.PrependFloat32Slot(4, temperatureC, 0.0)

def AddTemperatureC(builder, temperatureC):
    StatusAddTemperatureC(builder, temperatureC)

def StatusEnd(builder):
    return builder.EndObject()

def End(builder):
    return StatusEnd(builder)
