# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gpsdo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class kf_correction_debug(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = kf_correction_debug()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAskf_correction_debug(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # kf_correction_debug
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # kf_correction_debug
    def Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # kf_correction_debug
    def HX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # kf_correction_debug
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # kf_correction_debug
    def S(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # kf_correction_debug
    def MahalanobisD2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # kf_correction_debug
    def Nis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # kf_correction_debug
    def Rejected(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def kf_correction_debugStart(builder):
    builder.StartObject(7)

def Start(builder):
    kf_correction_debugStart(builder)

def kf_correction_debugAddZ(builder, z):
    builder.PrependFloat32Slot(0, z, 0.0)

def AddZ(builder, z):
    kf_correction_debugAddZ(builder, z)

def kf_correction_debugAddHX(builder, hX):
    builder.PrependFloat32Slot(1, hX, 0.0)

def AddHX(builder, hX):
    kf_correction_debugAddHX(builder, hX)

def kf_correction_debugAddY(builder, y):
    builder.PrependFloat32Slot(2, y, 0.0)

def AddY(builder, y):
    kf_correction_debugAddY(builder, y)

def kf_correction_debugAddS(builder, s):
    builder.PrependFloat32Slot(3, s, 0.0)

def AddS(builder, s):
    kf_correction_debugAddS(builder, s)

def kf_correction_debugAddMahalanobisD2(builder, mahalanobisD2):
    builder.PrependFloat32Slot(4, mahalanobisD2, 0.0)

def AddMahalanobisD2(builder, mahalanobisD2):
    kf_correction_debugAddMahalanobisD2(builder, mahalanobisD2)

def kf_correction_debugAddNis(builder, nis):
    builder.PrependFloat32Slot(5, nis, 0.0)

def AddNis(builder, nis):
    kf_correction_debugAddNis(builder, nis)

def kf_correction_debugAddRejected(builder, rejected):
    builder.PrependBoolSlot(6, rejected, 0)

def AddRejected(builder, rejected):
    kf_correction_debugAddRejected(builder, rejected)

def kf_correction_debugEnd(builder):
    return builder.EndObject()

def End(builder):
    return kf_correction_debugEnd(builder)
