# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gpsdo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class kf_debug(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = kf_debug()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAskf_debug(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # kf_debug
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # kf_debug
    def TimestampS(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # kf_debug
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from gpsdo.kf_state_debug import kf_state_debug
            obj = kf_state_debug()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # kf_debug
    def Correction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from gpsdo.kf_correction_debug import kf_correction_debug
            obj = kf_correction_debug()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # kf_debug
    def K(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from gpsdo.Mat3x1 import Mat3x1
            obj = Mat3x1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # kf_debug
    def H(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from gpsdo.Mat1x3 import Mat1x3
            obj = Mat1x3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # kf_debug
    def Q(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from gpsdo.Mat3x3 import Mat3x3
            obj = Mat3x3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # kf_debug
    def R(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # kf_debug
    def OutlierCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # kf_debug
    def KfIteration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def kf_debugStart(builder):
    builder.StartObject(9)

def Start(builder):
    kf_debugStart(builder)

def kf_debugAddTimestampS(builder, timestampS):
    builder.PrependFloat64Slot(0, timestampS, 0.0)

def AddTimestampS(builder, timestampS):
    kf_debugAddTimestampS(builder, timestampS)

def kf_debugAddState(builder, state):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(state), 0)

def AddState(builder, state):
    kf_debugAddState(builder, state)

def kf_debugAddCorrection(builder, correction):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(correction), 0)

def AddCorrection(builder, correction):
    kf_debugAddCorrection(builder, correction)

def kf_debugAddK(builder, k):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(k), 0)

def AddK(builder, k):
    kf_debugAddK(builder, k)

def kf_debugAddH(builder, h):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(h), 0)

def AddH(builder, h):
    kf_debugAddH(builder, h)

def kf_debugAddQ(builder, q):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(q), 0)

def AddQ(builder, q):
    kf_debugAddQ(builder, q)

def kf_debugAddR(builder, r):
    builder.PrependFloat32Slot(6, r, 0.0)

def AddR(builder, r):
    kf_debugAddR(builder, r)

def kf_debugAddOutlierCount(builder, outlierCount):
    builder.PrependUint32Slot(7, outlierCount, 0)

def AddOutlierCount(builder, outlierCount):
    kf_debugAddOutlierCount(builder, outlierCount)

def kf_debugAddKfIteration(builder, kfIteration):
    builder.PrependUint32Slot(8, kfIteration, 0)

def AddKfIteration(builder, kfIteration):
    kf_debugAddKfIteration(builder, kfIteration)

def kf_debugEnd(builder):
    return builder.EndObject()

def End(builder):
    return kf_debugEnd(builder)
