# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gpsdo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class kf_state_debug(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = kf_state_debug()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAskf_state_debug(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # kf_state_debug
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # kf_state_debug
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from gpsdo.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # kf_state_debug
    def P(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from gpsdo.Mat3x3 import Mat3x3
            obj = Mat3x3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # kf_state_debug
    def Drift(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def kf_state_debugStart(builder):
    builder.StartObject(3)

def Start(builder):
    kf_state_debugStart(builder)

def kf_state_debugAddX(builder, x):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0)

def AddX(builder, x):
    kf_state_debugAddX(builder, x)

def kf_state_debugAddP(builder, p):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(p), 0)

def AddP(builder, p):
    kf_state_debugAddP(builder, p)

def kf_state_debugAddDrift(builder, drift):
    builder.PrependFloat32Slot(2, drift, 0.0)

def AddDrift(builder, drift):
    kf_state_debugAddDrift(builder, drift)

def kf_state_debugEnd(builder):
    return builder.EndObject()

def End(builder):
    return kf_state_debugEnd(builder)
