# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gpsdo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Mat3x1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Mat3x1()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMat3x1(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Mat3x1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Mat3x1
    def M(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Mat3x1
    def MAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Mat3x1
    def MLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Mat3x1
    def MIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Mat3x1Start(builder):
    builder.StartObject(1)

def Start(builder):
    Mat3x1Start(builder)

def Mat3x1AddM(builder, m):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(m), 0)

def AddM(builder, m):
    Mat3x1AddM(builder, m)

def Mat3x1StartMVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMVector(builder, numElems):
    return Mat3x1StartMVector(builder, numElems)

def Mat3x1End(builder):
    return builder.EndObject()

def End(builder):
    return Mat3x1End(builder)
