# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gpsdo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Status(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Status()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatus(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Status
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Status
    def PhaseCnt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Status
    def FreqErrorHz(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Status
    def FreqDriftHzS(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Status
    def VoltageControlV(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Status
    def VoltageMeasuredV(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Status
    def TemperatureC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Status
    def RawCounterValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def StatusStart(builder):
    builder.StartObject(7)

def Start(builder):
    StatusStart(builder)

def StatusAddPhaseCnt(builder, phaseCnt):
    builder.PrependFloat32Slot(0, phaseCnt, 0.0)

def AddPhaseCnt(builder, phaseCnt):
    StatusAddPhaseCnt(builder, phaseCnt)

def StatusAddFreqErrorHz(builder, freqErrorHz):
    builder.PrependFloat32Slot(1, freqErrorHz, 0.0)

def AddFreqErrorHz(builder, freqErrorHz):
    StatusAddFreqErrorHz(builder, freqErrorHz)

def StatusAddFreqDriftHzS(builder, freqDriftHzS):
    builder.PrependFloat32Slot(2, freqDriftHzS, 0.0)

def AddFreqDriftHzS(builder, freqDriftHzS):
    StatusAddFreqDriftHzS(builder, freqDriftHzS)

def StatusAddVoltageControlV(builder, voltageControlV):
    builder.PrependFloat32Slot(3, voltageControlV, 0.0)

def AddVoltageControlV(builder, voltageControlV):
    StatusAddVoltageControlV(builder, voltageControlV)

def StatusAddVoltageMeasuredV(builder, voltageMeasuredV):
    builder.PrependFloat32Slot(4, voltageMeasuredV, 0.0)

def AddVoltageMeasuredV(builder, voltageMeasuredV):
    StatusAddVoltageMeasuredV(builder, voltageMeasuredV)

def StatusAddTemperatureC(builder, temperatureC):
    builder.PrependFloat32Slot(5, temperatureC, 0.0)

def AddTemperatureC(builder, temperatureC):
    StatusAddTemperatureC(builder, temperatureC)

def StatusAddRawCounterValue(builder, rawCounterValue):
    builder.PrependUint32Slot(6, rawCounterValue, 0)

def AddRawCounterValue(builder, rawCounterValue):
    StatusAddRawCounterValue(builder, rawCounterValue)

def StatusEnd(builder):
    return builder.EndObject()

def End(builder):
    return StatusEnd(builder)
